routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

/**  FRONTEND SECION **/
Route::get('/clear-cache', function () {
	Artisan::call('config:cache');
	return "Cache is cleared";
});

Route::get('', function () {
	return redirect('/login');
});

/* Synopsis Titlen front end */

Route::get('/synopsis-title', 'SynopsisController@synopsysTitle')->name('synopsys.title');


/*BOS Manual Send*/
Route::get('thesis-status/change', 'Admin\UserController@updateAssignThesis');
Route::get('thesis-reassignedtest', 'Admin\UserController@getAndUpdatedjudicatorsCollege');
Route::get('thesis-reassigned', 'Admin\UserController@theisReAssign');
Route::get('check-count', 'Admin\UserController@userReminder');
Route::get('adjudicator-auto-thesis', 'Admin\UserController@assingAdjudicatorAutomatic');
Route::get('adjudicator-states-update', 'Admin\UserController@adjudicatorStateUpdate');
Route::get('adjudicator-states', 'Admin\UserController@getAdjudicatorList');
Route::get('bos/manual-send', 'Admin\UserController@sendManuallToBOSMember');
/* Adjudicator manually send*/
Route::get('adjudicator/assign-link', 'Admin\UserController@sendAdjudicatorReminderAssign');
Route::get('adjudicator/report-reminder', 'Admin\UserController@sendAdjudicatorPendingreport');
Route::get('manually/remove-student', 'SynopsisController@changeEnableStatus');
/**/

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/registration', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/registration', 'Auth\RegisterController@register');
Route::get('/otp-form', 'Auth\LoginController@showOtpForm');
Route::get('otp-resend', 'Auth\LoginController@otpResend')->name('otp-resend');
Route::post('otp-verification', 'Auth\LoginController@otpVerification')->name('otp-verification');
Route::get('/synopsis-manual', 'SynopsisController@downloadSynossisManual');
Route::post('registration-no/check', 'Auth\RegisterController@checkRegistrationNo');

Route::get('import-export', 'TestController@importExport');
Route::any('import', 'TestController@import');

Route::get('export', 'TestController@export');

Route::get('/email-verification/{token}'
	, 'Auth\LoginController@emailVerifyLogin');
Route::get('/forgot-password', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('/forgot-password', 'Auth\ForgotPasswordController@sendResetLink');
Route::get('/reset-password/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::post('reset-password', 'Auth\ResetPasswordController@storeResetPassword');

Route::get('/payment/history')->name('student-payment.history');

Route::post('/return-payment', 'paymentController@returnPayment');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('dashboard', 'DashboardController');
	Route::get('rejection-list', 'StudentProfileController@rejectionList')->name('rejection-list');

	Route::get('/test/payment-check', 'paymentController@testCheck');
	Route::post('/category/add', 'SynopsisController@addCategory')->name('category.student-add');

	Route::get('/synopsis/testpdf', 'SynopsisController@test');
	Route::get('/set-registration-no', 'paymentController@setRegistrationNo');
	Route::get('/check-registration-no', 'paymentController@checkRegistration');

	Route::get('/check-unique-no', 'SynopsisController@setUniqueNo');

	Route::post('synopsis/file-upload', 'SynopsisController@uploadPDF');
	Route::get('/synopsis/other-pdf/{pdf}', 'SynopsisController@viewOherpdf');
	Route::get('/dissertation/other-pdf/{pdf}', 'ThesisController@viewOherpdf');
	Route::post('/synopsis/save-signature', 'SynopsisController@saveSignature');
	Route::post('/dissertation/save-signature', 'SynopsisController@saveSignature');

	Route::get('/get-subcategory', 'paymentController@getSubCategory');
	Route::get('synopsis/old-data/{id}', 'SynopsisController@oldSynopsisPayment');
	Route::get('dissertation/old-data/{id}', 'ThesisController@oldThesisPayment');
	Route::get('synopsis/view-pdf', 'SynopsisController@viewPdf')->name('synopsis.view-pdf');
	Route::get('dissertation/view-pdf', 'ThesisController@viewPdf')->name('thesis.view.pdf');
	Route::resource('synopsis', 'SynopsisController');
	Route::resource('dissertation', 'ThesisController');
	Route::resource('profile', 'StudentProfileController');
	Route::get('change-password', 'StudentProfileController@changePassword');
	Route::post('change-password', 'StudentProfileController@changePasswordStore');
	Route::get('support', 'StudentProfileController@support');
	Route::post('support', 'StudentProfileController@supportStore');

	Route::put('thesis-file/resubmit/{id}', 'ThesisController@thesisFileResubmit')->name('thesis-file.resubmit');
	Route::get('payment/history', 'paymentController@getSudentPayment')->name('student-pay.history');

	Route::get('get/thesis-status', 'ThesisController@submittedStatus')->name('get.thesis-status');
	Route::get('get/download-reason/doc', 'ThesisController@viewReasonRejectDownload');

	Route::put('update/synopsis-file/{id}', 'SynopsisController@updateSynossisFile')->name('update.synopsis-file');
	//Route::resource('payment', 'paymentController');
	Route::get('synopsis/payment/create', 'paymentController@createSynopsis')->name('synopsis.payment.create');
	Route::get('dissertation/payment/create', 'paymentController@create')->name('thesis.payment.create');
	Route::post('/payment', 'paymentController@store')->name('payment.store');

	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	Route::get('/success-message/{type}/{paid_type}', 'paymentController@successMessage')->name('success-message');
	Route::get('/download-reason/doc', 'StudentProfileController@downloadReason');

	Route::get('/check', 'paymentController@check');
});

/**  ADMIN SECTION **/

Route::get('/admin/login', 'Admin\AuthController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Admin\AuthController@storeLogin');

Route::get('/admin/forget-password', 'Admin\AuthController@forgetpassword');
Route::post('/admin/forget-password', 'Admin\AuthController@forgetPasswordStore');

Route::get('/admin/reset-password/{token}', 'Admin\AuthController@showResetForm');
Route::post('admin/reset-password', 'Admin\AuthController@storeResetPassword');

Route::get('/admin/registration', 'Admin\AuthController@showRegisterForm')->name('admin.register');
Route::post('/admin/registration', 'Admin\AuthController@storeRegistration')->name('admin.register.store');
Route::get('admin/reviewer-success', 'Admin\AuthController@registerSuccess')->name('admin.messages');
Route::get('admin/email-verification/{token}'
	, 'Admin\AuthController@emailVerifyLogin');

Route::get('admin/acknowledge/{id}/{token}', 'Admin\AcknowledgeController@acknowledge');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
	Route::get('/mail-send/adjudicator', 'UserController@sendLoginCredentialToAdjudicator');
	Route::get('/', 'DashboardController@index')->name('admin.dashboard');
	Route::get('/dashboard-data', 'DashboardController@dashboardData');
	Route::get('/logout', 'AuthController@logout')->name('admin.logout');

	Route::get('/user-manage', 'UserController@index')->name('user-manage.index')->middleware('admin.roles:user-list');
	Route::get('pending/adjudicator-list/{id}', 'UserController@getPendingAdjudicatorList');
	Route::get('thesis/student-list/{id}', 'UserController@coursewiseStudentList')->name('admin.student.thesis_list');
	Route::get('thesis/cat/student-list/{id}', 'UserController@categoryWiseStudentList')->name('admin.student.thesis_list');

	Route::get('/user-manage/profile', 'UserController@Profile')->name('user-manage.profile')->middleware('admin.roles:user-list');
	Route::get('/user-manage/create', 'UserController@create')->name('user-manage.create')->middleware('admin.roles:user-create');
	Route::post('/user-manage', 'UserController@store')->name('user-manage.store')->middleware('admin.roles:user-create');
	Route::get('/user-manage/{user_manage}/edit', 'UserController@edit')->name('user-manage.edit')->middleware('admin.roles:user-edit');
	Route::put('/user-manage/{user_manage}', 'UserController@update')->name('user-manage.update')->middleware('admin.roles:user-edit');
	Route::delete('/user-manage/{user_manage}', 'UserController@destroy')->name('user-manage.destroy')->middleware('admin.roles:user-delete');

	Route::get('user/password-set/{id}', 'UserController@setUserDefaultPassword')->name('user-manage.set_dafault.password');

	Route::get('export/user-list', 'UserController@getUserExcel');
	Route::get('/student-payments-export', 'usercontroller@studentpaymentexport')->name('student.payment-export');

	Route::get('/withdraw-dissertation', 'UserController@DissertationWithdraw')->name('admin.dissertation.withdraw');

	Route::get('/view-category/{id}', 'UserController@viewSpeciality');

	Route::post('/send-email', 'UserController@sendEmail');

	Route::get('resubmit-synopsis/enable/{id}', 'UserController@enableResubmitSynopsis');

	Route::get('/user-resubmit', 'UserController@userResubmit')->name('admin.user-resubmit');
	//Route::get('/reviewer-accept', 'ReviewerController@reviewerAccept')->name('admin.reviewer-accept');

	Route::post('/synopsis/change-status', 'UserController@synopsisChangeStatus')->name('student.synopsis.status-change');

	Route::get('/reason-rejected/view', 'UserController@viewReasonReject');

	Route::get('/manage-role', 'RoleController@index')->name('manage-role.index')->middleware('admin.roles:role-list');

app/Models/Support.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Support extends Authenticatable {
	use SoftDeletes;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $table = 'support';
	protected $fillable = [
		'user_id', 'subject', 'content', 'status', 'admin_reply'	];

	/**
	 * The attributes that should be hidden for arrays.
	 *
	 * @var array
	 */
	
	public function userDetail() {
		return $this->belongsTo(User::class, 'user_id','id');
	}

	public function roles() {
		return $this->belongsToMany(Role::class, 'role_users');
	}

	/**
	 * Checks if User has access to $permissions.
	 */
	public function hasAccess(array $permissions): bool {
		// check if the permission is available in any role
		foreach ($this->roles as $role) {
			if ($role->hasAccess($permissions)) {
				return true;
			}
		}
		return false;
	}

	/**
	 * Checks if the user belongs to role.
	 */
	public function inRole(string $roleSlug) {
		return $this->roles()->where('slug', $roleSlug)->count() == 1;
	}

	public function getFullNameAttribute() {
		return $this->f_name . ' ' . $this->l_name;
	}

	

	

}

resources/views/frontend/dashboard.blade.php
@extends('frontend.layout')
@section('content')
<section class="desh-bord">
   <div class="container">
      @if(Session::has('msg'))
      <div class="alert alert-success">
         <strong>{{Session('msg')}}</strong>
      </div>
      @endif
      @if(Session::has('status'))
      <div class="alert alert-success" role="alert">
         {{ session('status') }}
      </div>
      @endif
      <div class="row">
         @include('frontend.includes.sidemenu')
         <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
          <h3 class="dashboard_title">Dashboard</h3>
            @if(\Auth::user()->studentSynopsis && \Auth::user()->studentSynopsis->status == 3)
            <div class="alert alert-danger">
              <strong>Synopsis Rejected!</strong> Your Synopsis has been Rejected.
            </div>
            @elseif(\Auth::user()->studentSynopsis && \Auth::user()->studentSynopsis->status == 4)
            <div class="alert alert-danger">
              <strong>Synopsis Send for revision!</strong> Your Synopsis has not been accepted please Resubmit again.
            </div>
            @endif
            @if(Auth::user()->studentThesis && \Auth::user()->studentThesis->status ==4)
            <div class="alert alert-danger">
              <strong>Dissertation Send for revision!</strong> Your Dissertation has not been accepted please Resubmit again.
            </div>
            @endif
            <div class="right-pnl">
               <ul>
               <!-- check user not submit thesis -->
               @if(!@Auth::user()->studentThesis && !@Auth::user()->studentThesis->is_paid)
                  <li>
                     <div class="lft">
                        <h4>{{\Auth::user()->studentSynopsis()->count()}}</h4>
                        @if(\Auth::user()->studentSynopsis && \Auth::user()->studentSynopsis->is_paid)
                        @if(\Auth::user()->studentSynopsis->status ==4)
                        <a href="{{route('synopsis.edit',['id'=>\Auth::user()->studentSynopsis->id])}}" class="{{(Request::is('synopsis')||Request::is('synopsis/*'))? 'active': ''}}"><i class="fa fa-files-o" aria-hidden="true"></i> Synopsis Submission</a>
                        @else
                        <span><a href="{{url('synopsis',[\Auth::user()->studentSynopsis])}}">Synopsis</a></span>
                        @endif
                        @elseif(\Auth::user()->studentSynopsis && \Auth::user()->studentSynopsis->is_paid ==0)
                        <span><a href="{{url('synopsis/old-data',['id'=>\Auth::user()->studentSynopsis->id])}}">Synopsis</a></span>
                        @else
                        <span><a href="{{url('synopsis/create')}}">Synopsis</a></span>
                        @endif
                     </div>
                     <div class="right">
                        <span class="icon"><i class="fa fa-book" aria-hidden="true"></i></span>
                     </div>
                  </li>

                  @endif
                  <!-- END -->

                  {{--@if(\Auth::user()->studentSynopsis && \Auth::user()->studentSynopsis->status ==2)--}}
                  <!-- check user has thesis-->
                 {{-- @if(@Auth::user()->studentThesis && @Auth::user()->studentThesis->is_paid) --}}
                  <li>
                     <div class="lft">
                        <h4>{{\Auth::user()->studentThesis()->count()}}</h4>
                        @if(\Auth::user()->studentThesis && \Auth::user()->studentThesis->is_paid)
                        <span><a href="{{\Auth::user()->studentThesis->status ==4? route('dissertation.edit',['id'=>\Auth::user()->studentThesis]): url('dissertation',[\Auth::user()->studentThesis])}}">Dissertation</a> </span>
                        @elseif(\Auth::user()->studentThesis && \Auth::user()->studentThesis->is_paid ==0)
                        <span><a href="{{url('dissertation/old-data',['id'=>\Auth::user()->studentThesis->id])}}">Dissertation</a></span>
                        @else
                        <span><a href="{{url('dissertation/create')}}">Dissertation</a> </span>
                        @endif
                     </div>
                     <div class="right">
                        <span class="icon"><i class="fa fa-file-text-o" aria-hidden="true"></i></span>
                     </div>
                  </li>

                 {{--  @endif --}}
                  <!-- END -->

                  {{--@endif--}}
                  <!-- <li>
                     <div class="lft">
                        <h4>14</h4>
                        <span>VAT Check Done</span>
                     </div>
                     <div class="right">
                        <span class="icon"><i class="fa fa-check" aria-hidden="true"></i></span>
                     </div>
                  </li> -->
               </ul>
            </div>
         </div>
      </div>
   </div>
</section>
@endsection

resources/views/frontend/import.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 5.7 Import Export Excel to database - Tuts Make</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
</head>
<body>
    
<div class="container">
    <div class="card mt-4">
        <div class="card-header">
            Laravel 5.7 Import Export Excel to database - Tuts Make
        </div>
        <div class="card-body">
            <form action="{{ url('import') }}" method="POST" name="importform" 
               enctype="multipart/form-data">
                @csrf
                <input type="file" name="file" class="form-control">
                <br>
                <a class="btn btn-info" href="{{ url('export') }}"> 
                 Export File</a>
                <button class="btn btn-success">Import File</button>
            </form>
        </div>
    </div>
</div>
    
</body>
</html>

resources/views/frontend/success-message.blade.php
@extends('frontend.layout')
@section('content')


<section class="desh-bord">
   <div class="container">
      <div class="row">
         {{--@include('frontend.includes.sidemenu')--}}
         <div class="col-md-12 col-sm-12 col-xs-12">
         	<div class="thankyouOuter">
         		<img src="{{url('public/img/thankcheck.png')}}" alt="thankcheck">
               @if($type ==1)
         		<p>Your Synopsis has been submitted succesfully.</p>
               @else
               <p>Your Dissertation has been submitted succesfully.</p>
               @endif

               @if($paid_type =='offline')
                  <p>You have paid by offline. So after paying fees your {{($type ==1? 'Synopsis':'Dissertation')}} will be procced.</p>
               @endif
         		<a href="{{route('dashboard.index')}}">Go To dashboard</a>
         	</div>
         </div>
      </div>
   </div>
</section>

@endsection

resources/views/frontend/synopsis-form.blade.php
@extends('frontend.layout')
@section('content')
@php
$currentRoute = Route::currentRouteName();
@endphp
<style>
   .kbw-signature { width: 400px; height: 100px; }
   #append_more_pdf{float: right;width: 62%;margin: 10px 0 10px 10px}
   #append_more_pdf .form-group{width: 100%; margin: 0;}
   #append_more_pdf .form-group > input{width: 100%;}
</style>
<section class="desh-bord">
   <div class="container">
      @if(Session::has('error'))
      <div class="alert alert-danger">
         <strong>{{Session('error')}}</strong>
      </div>
      @endif
      <div class="row">
         @include('frontend.includes.sidemenu')
         <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
          <h3 class="dashboard_title">Synopsis Form Submission</h3>
            <div class="right-pnl">

               <form action="{{route('synopsis.store')}}" method="post" enctype="multipart/form-data" onsubmit="return studentform(event)">
                  @csrf
                  <div class="form-group @if($errors->first('category_id')) has-error @endif">
                     <!-- <div class="category-add">
                        <a href="" data-toggle="modal" data-target="#synopModal"><i class="fa fa-plus"></i> Add Category</a>
                     </div> -->
                     <div class="category-label">
                        <label for="category_id">Category <span class="require-asterik">*</span>:</label>
                     </div>
                     @php $catUrl =url('get-subcategory'); @endphp
                     <select class="form-control" name="category_id" id="category_id" onchange="getSubCategory(this, '{{$catUrl}}')">
                        <option value="">Select Category</option>
                        @foreach( $parentCategory as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                     </select>

                  </div>
                  <div class="form-group" id="subcat_div">
                     <div class="category-label">
                        <label for="category_id">Sub Category <span class="require-asterik">*</span>:</label>
                     </div>
                     <select class="form-control" name="sub_category" id="add_sub_cat" onchange="getSubCategory(this, '{{$catUrl}}')">
                        <option value="">Select Sub Category</option>
                     </select>

                  </div>

                  <div class="form-group">
                     <div class="category-label">
                        <label for="add_course">Category Name <span class="require-asterik">*</span>:</label>
                     </div>
                     <select class="form-control" name="course_name" id="add_course">
                        <option value="">Select Course</option>
                     </select>

                  </div>

                  <!--<div id="add_sub_cat"></div>-->
                  <!--<div id="add_course"></div>-->
                  <div class="form-group @if($errors->first('name_of_student')) has-error @endif">
                     <label for="name_of_student">Name of the Student <span class="require-asterik">*</span>:</label>
                     @php $checknameUrl =url('set-registration-no'); @endphp
                     <input type="text" class="form-control" id="name_of_student" placeholder="Enter Student Name" name="name_of_student" value="{{(old('name_of_student'))?old('name_of_student'):\Auth::user()->full_name}}" onblur="checkRegistration(this.value, '{{$checknameUrl}}')">

                  </div>
                  <div class="form-group @if($errors->first('registration_no')) has-error @endif">
                   @php $checknameUrl =url('check-unique-no'); @endphp
                     <label for="registration_no">WBUHS Reg. No./ Unique Id <span class="require-asterik">*</span>:&nbsp;@if(!@\Auth::user()->userDetail->registration_no)<a href="javascript:void(0)" onclick="checkRegistration( '{{$checknameUrl}}')">Check your Unique Id</a>@endif</label>
                     @php $checkregistrationUrl =url('check-registration-no'); @endphp
                     <input type="text" class="form-control" id="registration_no" placeholder="Enter Registration No / Unique Id" name="registration_no" value="{{@\Auth::user()->userDetail->registration_no}}" readonly="true">

                  </div>
                  <div class="form-group @if($errors->first('registration_year')) has-error @endif">
                     <label for="registration_year">WBUHS Reg. Year :</label>
                     <input type="text" class="form-control" id="registration_year" placeholder="Enter Registration Year" name="registration_year" value="{{old('registration_year')}}">

                  </div>
                  <div class="form-group @if($errors->first('institute_name')) has-error @endif">
                     <label for="institute_name">Name of the Institution <span class="require-asterik">*</span>:</label>
                     <select class="form-control" name="institute_name" id="institute_name">
                              <option value="">Select College Name</option>
                              @foreach($college_masters as $college)
                              <option value="{{$college['id']}}">{!! $college['college_name']!!}</option>
                              @endforeach
                           </select>
                     {{--  <input type="text" class="form-control" id="institute_name" placeholder="Enter Institute Name" name="institute_name" value="{{old('institute_name')}}">--}}

                  </div>
                  <div class="form-group @if($errors->first('mobile_landline')) has-error @endif">
                     <label for="mobile_landline">Cell Phone <span class="require-asterik">*</span>:</label>
                     <input type="text" class="form-control" id="mobile_landline" placeholder="Enter Mobile / Land No" name="mobile_landline" value="{{(old('mobile_landline'))?old('mobile_landline'):\Auth::user()->userDetail->mobile}}" readonly>

                  </div>
                  <div class="form-group @if($errors->first('email')) has-error @endif">
                     <label for="email">E-mail <span class="require-asterik">*</span>:</label>
                     <input type="email" class="form-control" id="email" placeholder="Enter Email" name="email" value="{{(old('email'))?old('email'):\Auth::user()->email}}" readonly>

                  </div>

                   <div class="form-group @if($errors->first('dob')) has-error @endif">
                     <label for="dob">DOB.<span class="require-asterik">*</span>:</label>
                     <input type="text" class="form-control datepicker_dob" id="dob" placeholder="DOB" name="dob" value="{{(old('dob'))?old('dob'):@Auth::user()->userDetail->dob}}" readonly>

                  </div>
                  <div class="form-group @if($errors->first('guide_name')) has-error @endif">
                     <label for="guide_name">Guide Name <span class="require-asterik">*</span>:</label>
                     <input type="text" class="form-control" id="guide_name" placeholder="Enter Guide Name" name="guide_name" value="{{old('guide_name')}}">

                  </div>
                  <div class="form-group @if($errors->first('guide_designation')) has-error @endif">
                     <label for="guide_designation">Guide Designation <span class="require-asterik">*</span>:</label>
                     <input type="text" class="form-control" id="guide_designation" placeholder="Enter Guide Designation" name="guide_designation" value="{{old('guide_designation')}}">

                  </div>
                  <div class="form-group">
                     <label for="co_guide_name">Co-Guides Name:</label>
                     <input type="text" class="form-control" id="co_guide_name" placeholder="Enter Co Guide Name" name="co_guide_name" value="{{old('co_guide_name')}}">
                  </div>
                  <div class="form-group">
                     <label for="co_guide_designation">Co-Guides Designation:</label>
                     <input type="text" class="form-control" id="co_guide_designation" placeholder="Enter Co Guide Designation" name="co_guide_designation" value="{{old('co_guide_designation')}}">
                  </div>
                  <div class="form-group @if($errors->first('proposed_title_thesis')) has-error @endif">
                     <label for="proposed_title_thesis">Proposed Title<span class="require-asterik">*</span>:</label>
                     <textarea class="form-control" name="proposed_title_thesis" id="proposed_title_thesis">{{old('proposed_title_thesis')}}</textarea>

                  </div>
                  <div class="form-group @if($errors->first('proposed_work_place')) has-error @endif">
                     <label for="proposed_work_place">Proposed place of work <span class="require-asterik">*</span>:</label>
                     <textarea class="form-control" name="proposed_work_place" id="proposed_work_place">{{old('proposed_work_place')}}</textarea>
                     @if($errors->first('proposed_work_place'))
                     <span class="error">{{$errors->first('proposed_work_place')}}</span>
                     @endif
                  </div>
                  <div class="form-group @if($errors->first('student_pdf')) has-error @endif">
                     <label for="proposed_work_place">Upload PDF <span class="require-asterik">*</span>: (Add more PDF)<a href="javascript:void(0)" onclick="addMorePdf()"> <i class="fa fa-plus" style="font-size:18px"></i></a></label>
                     <input class="form-control" type="file" name="student_pdf" data-url="{{url('synopsis/file-upload')}}">
                     <div class="file-size">Max file size : 25 MB</div>
                     <div id="append_more_pdf">
                     </div>
                  </div>

                  <input type="hidden" name="student_signature" id="student_signature">
                  <div>
                     <label for="sig" class="signature-field">Signature <span class="require-asterik">*</span>: (or Upload Signature)<a href="javascript:void(0)" onclick="showSignUpload('signature_off')"> click</a></label>
                     <label for="sig" style="display: none;" class="signature-upload">Upload Signature <span class="require-asterik">*</span>: (or Signature)<a href="javascript:void(0)" onclick="showSignUpload('signature_on')"> click</a></label>
                     <div class="form-group signature-field">
                        <div id="sig"></div>
                     </div>
                      <p style="clear: both;" class="signature-field">
                         <a href="#" id="saveImage" data-url="{{url('synopsis/save-signature')}}"  onclick="signatureUpload('{{csrf_token()}}', event)">Save Signature</a>
                        <a href="#" id="clear">Clear</a>
                     </p>

                     <!-- <img src="" id="showsign" class="signature-field"> -->
                     <div class="form-group signature-upload" id="signature-image" style="display: none;">
                        <input type="file" name="signUpload" class="form-control">
                     </div>
                  </div>

                  <!-- <div id="sig"></div> -->
                  <div class="submitOuter">
                  <button type="submit" class="btn btn-primary submit-student" disabled="true">Submit Synopsis</button>
                  </div>
               </form>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- The Modal -->
<div class="modal fade" id="synopModal" role="dialog">
   <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><i class="fa fa-times"></i></button>
            <h4 class="modal-title">Add Category</h4>
         </div>
         <div class="modal-body">
            <form action="{{route('category.student-add')}}" id="category_modal" data-reload-url="{{route('synopsis.index')}}">
               @csrf
               <div class="form-group">
                  <label for="email">Category:</label>
                  <select class="form-control" name="parent">
                     <option value="0">Root Category</option>
                     @foreach( $categories as $category)
                     <option value="{{$category['id']}}">{!! $category['name'] !!}</option>
                     @endforeach
                  </select>
               </div>
               <div class="form-group">
                  <label for="name">Name:</label>
                  <input type="text" class="form-control"  name="name">
                  <span class="error" id="name"></span>
               </div>
            </form>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-primary" onclick="modalFormSubmit('category_modal')">Add &nbsp;<i class="fa fa-spinner fa-spin" style="font-size:20px; display: none;" id="spinner"></i></button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>
@endsection